name: almas_image
description: A new Flutter package.
version: 1.0.0
repository: https://github.com/Almas-Studio/almas_image
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter